import Link from "next/link";
import { redirect } from "next/navigation";
import { env } from "@/lib/env";
import { loadFacts } from "@/lib/sources/factbase";
import { isConfigured, product } from "@/lib/product";
import { listKill } from "@/lib/killswitch";
import { statusCounts, awaitingApproval } from "@/lib/queue";
import { toggleKillAction, markReviewedAction } from "@/app/actions";

export const dynamic = "force-dynamic";

function DbHint({ error }: { error: string }) {
  return (
    <div className="note">
      <strong>Database not reachable.</strong>
      <p className="dim" style={{ margin: "6px 0 0" }}>
        Set <code>DATABASE_URL</code> in <code>.env.local</code> and run{" "}
        <code>npm run db:migrate</code>. See <code>SETUP.md §1.4</code>.
      </p>
      <p className="dim" style={{ margin: "6px 0 0", fontSize: 12 }}>
        {error}
      </p>
    </div>
  );
}

export default async function Overview() {
  if (!isConfigured()) redirect("/setup");
  const cfg = product();
  const posture = {
    growthHalt: env.growthHalt,
    dryRun: env.dryRun,
    liveChannels: [...env.liveChannels],
    factbase: loadFacts().version,
    genModel: env.genModel,
    criticModel: env.criticModel,
  };

  let kill: Awaited<ReturnType<typeof listKill>> | null = null;
  let counts: Record<string, number> = {};
  let pending = 0;
  let dbError = "";
  try {
    [kill, counts] = await Promise.all([listKill(), statusCounts()]);
    pending = (await awaitingApproval()).length;
  } catch (e) {
    dbError = (e as Error).message;
  }

  return (
    <main>
      <h1>Overview</h1>

      {!cfg.reviewed && (
        <div className="card" style={{ borderColor: "var(--bad)" }}>
          <strong>Factbase not reviewed.</strong>
          <p className="dim" style={{ margin: "6px 0 10px", fontSize: 13 }}>
            This product config was generated by setup and has not been signed
            off. Every channel is forced to dry-run until you review the{" "}
            <Link href="/facts">fact base</Link>, the guardrail file
            (product/factbase/banned-claims.json), and product.json — then
            confirm here. This gate overrides DRY_RUN and LIVE_CHANNELS.
          </p>
          <form action={markReviewedAction}>
            <button className="primary" type="submit">
              I reviewed the fact base — arm live posture
            </button>
          </form>
        </div>
      )}

      {pending > 0 && (
        <div className="card" style={{ borderColor: "var(--warn)" }}>
          <strong>{pending}</strong> item{pending === 1 ? "" : "s"} awaiting your
          approval. <Link href="/queue">Review now →</Link>
        </div>
      )}

      <h2>Posture</h2>
      <div className="card">
        <div className="row">
          <span className={`pill ${posture.growthHalt ? "bad" : "good"}`}>
            {posture.growthHalt ? "GROWTH_HALT — engine off" : "engine armed"}
          </span>
          <span className={`pill ${posture.dryRun ? "warn" : "good"}`}>
            {posture.dryRun
              ? "unlisted channels: dry-run"
              : "DRY_RUN=false (global go-live)"}
          </span>
          <span className="pill">
            live channels:{" "}
            {posture.liveChannels.length
              ? posture.liveChannels.join(", ")
              : "none"}
          </span>
        </div>
        <p className="dim" style={{ margin: "10px 0 0", fontSize: 12 }}>
          factbase {posture.factbase} · gen {posture.genModel} · critic{" "}
          {posture.criticModel}. Everything waits for approval in the Queue
          except changelog, which publishes on its own (git-revertable).
        </p>
      </div>

      {dbError ? (
        <DbHint error={dbError} />
      ) : (
        <>
          <h2>Kill switches</h2>
          <div className="card">
            {kill!.map((k) => (
              <div
                key={k.scope}
                className="row"
                style={{ padding: "6px 0", borderBottom: "1px solid var(--line)" }}
              >
                <span className={`pill ${k.enabled ? "good" : "bad"}`}>
                  {k.enabled ? "live" : "HALTED"}
                </span>
                <code>{k.scope}</code>
                <span className="dim" style={{ fontSize: 12 }}>
                  {k.reason ?? ""}
                </span>
                <form action={toggleKillAction} className="inline" style={{ marginLeft: "auto" }}>
                  <input type="hidden" name="scope" value={k.scope} />
                  <input type="hidden" name="enabled" value={String(!k.enabled)} />
                  <button className={k.enabled ? "ghost" : "primary"}>
                    {k.enabled ? "Halt" : "Resume"}
                  </button>
                </form>
              </div>
            ))}
            <p className="dim" style={{ margin: "10px 0 0", fontSize: 12 }}>
              <code>channel:*</code> pauses one type. <code>content</code> and{" "}
              <code>social</code> pause their whole group; <code>global</code>{" "}
              pauses everything. Paused rows wait and resume when re-enabled.
              If the dashboard itself is unreachable, set{" "}
              <code>GROWTH_HALT=1</code> in <code>.env.local</code>: it halts
              the tick before the database is even consulted.
            </p>
          </div>

          <h2>Queue</h2>
          <div className="card">
            {Object.keys(counts).length === 0 ? (
              <span className="empty">Queue is empty.</span>
            ) : (
              <div className="row">
                {Object.entries(counts).map(([s, n]) => (
                  <span key={s} className="pill">
                    {s}: <strong>&nbsp;{n}</strong>
                  </span>
                ))}
              </div>
            )}
            <p className="dim" style={{ margin: "10px 0 0", fontSize: 12 }}>
              Posting frequency, cap budgets, and what goes out next:{" "}
              <Link href="/cadence">Cadence →</Link>
            </p>
          </div>
        </>
      )}
    </main>
  );
}
